name: Build and Update READMEs

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build with PlatformIO
      run: pio run -e release
    
    - name: Commit updated READMEs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.*.md
        git commit -m "Update translated READMEs" || echo "Nothing to commit"
        git push
